### ISSUE TITLE
Things to do for v0.4

### ISSUE THREAD

**Issue by craaaa** [CS2103AUG2016-F11-C3/main#55]
## Fix existing things
- [x] Fix failing tests (cara but can u help pls)
- [x] Change `edit` command syntax (darren)
  - [x] Change user guide syntax & examples - pending PR #59
  - [x] Refactor `EditCommand` to use new syntax
- [x] Fix UI to show dates
  - [x] Add `DateTime` prettifier (darren) - pending PR #58 
  - [x] Add dates to UI (yuchuan)
- [x] Fix `done` command (duc)
## Extend existing things
- [x] Improve listing to do scoping (#38)
- [x] Change find command to find by other things (cara, #9)
  - [x] Find by keyword/tag
  - [x] Find by task type (?)
  - [x] Find by date (?)
- [ ] Edit deleteCommand to delete by keyword (cara)
## Make new things
- [x] Add new UML diagrams (duc)
- [ ] Do the sidebar
  - [ ] Create persistent list of most urgent items
  - [ ] Update UI
- [x] Add undo (#56) (duc)
  - [x] Implement stack for all commands
  - [x] Create reverse moves for:
    - [x] `add`
    - [x] `delete`
    - [x] `edit` 
    - [x] `done`
  - [x] Implement `UndoCommand`
- [ ] Syntax highlighting for commandBox (darren, related to #34)
- [x] Add tagging (#33) (cara)
